# -*- coding: utf-8 -*-
"""Shihab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V1c5Vl0cHdFCmRnVUY_uMvf7IbLnjq4t
"""

import pandas as pd
import numpy as np

df = pd.read_csv ('/content/Income Dataset (50k).csv')


dfn = df.fillna(0)


newdata = pd.get_dummies (dfn.workclass)


mergeddata = pd.concat ([dfn, newdata], axis= 'columns')


finaldata = mergeddata.drop (['workclass'], axis='columns')


from sklearn.linear_model import LinearRegression
modeldata = LinearRegression

a = finaldata.drop(['education','marital-status','occupation','relationship', 'race', 'gender','native-country'], axis='columns')


b=finaldata.drop (['fnlwgt'],axis='columns')


c = finaldata.fnlwgt

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    1.1, 1.0, test_size=0.20, random_state=0, stratify = predictor)